on:
  push:
    branches:
      - main

name: Auto Deploy to AWS Lambda

jobs:
  deploy:
    name: Auto Deploy
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Setup Golang
      uses: actions/setup-go@v1
      with:
        go-version: '1.16.4'

    - name: Install Dependencies
      run: |
        npm install serverless -g
        npm install

    - name: Build readLanking
      run: |
        mkdir -p ./readLanking/build ./readLanking/build/production
        cd readLanking && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o ./build/production/main main.go

    - name: Build updateLanking
      run: |
        mkdir -p ./updateLanking/build ./updateLanking/build/production
        cd updateLanking && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o ./build/production/main main.go

    - name: Deploy to Lambda
      run: |
        sls deploy --stage prod --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
